version: '3.8'

services:
  node:
    image: ${COMPOSE_PROJECT_NAME}/node:20-alpine
    build: services/node
    command: >
      /bin/sh -c "npm install &&
                  npm run migration:run &&
                  npm run start:debug"
    restart: on-failure
    ports:
      - '${APP_HTTP_PORT}:80'
    volumes:
      - ../:/var/www
    environment:
      - PM2_EXEC_MODE=${APP_PM2_EXEC_MODE}
      - PM2_INSTANCES=${APP_PM2_INSTANCES}
    depends_on:
      - postgres
    ulimits:
      core:
        hard: 0
        soft: 0
  postgres:
    image: postgres:15-alpine
    restart: on-failure
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./services/postgres/multiple-databases:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_MULTIPLE_DATABASES
volumes:
  postgres:
